### ISSUE TITLE
Should we archive? 

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/budget-api#24]
Given intent to remove from Blink, should this repo be archived? https://groups.google.com/a/chromium.org/d/msg/blink-dev/18r3whCBv0I/b8qrtFTsDAAJ

**Comment by beverloo** [comment]
Yeah, I was going to request that next. Let me add a note to the draft.

**Comment by beverloo** [comment]
https://wicg.github.io/budget-api/ ta-dum.

Marcos, can I archive the repo or is that something you have to do?

**Comment by marcoscaceres** [comment]
If you can access the repo settings, you might be able to do it. If not, let me know.

**Comment by beverloo** [comment]
You're right, I have the button. Let's do it, thanks! :)
